services:
  indomitus_ground_station:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: humble
    image: indomitus-ground-station:humble
    container_name: indomitus_ground_station
    network_mode: host
    stdin_open: true      # -i
    tty: true             # -t
    privileged: true
    environment:
      - ROS_DOMAIN_ID=90
      - ROS_LOCALHOST_ONLY=0
      - JOY_BOARD_PORT=${JOY_BOARD_PORT:-/dev/ttyACM0}
      - BUTTON_BOARD_PORT=${BUTTON_BOARD_PORT:-/dev/ttyACM1}
    volumes:
      - ./:/work:rw
      - ./src:/opt/ws/src:rw
      - /dev:/dev
    group_add:
      - dialout

