#!/usr/bin/env bash
#
# Generates the Fast DDS profile that pins DDS traffic to the rover link.
#
# Why this exists: the ground station laptop normally has two live interfaces —
# the rover link (a USB WiFi adapter on 10.42.0.0/24) and whatever provides
# internet. Fast DDS announces unicast locators for *every* interface it can
# see, so the rover picks one and aims user data at it. When it picks the
# internet-side address, that address is not routable from the rover and every
# sample is dropped, while discovery keeps working perfectly over multicast.
#
# The result is the worst kind of failure: `ros2 node list`, `ros2 node info`
# and `ros2 topic info -v` all look completely healthy — correct types, correct
# QoS, correct publisher counts — and `ros2 topic hz` reports nothing on any
# topic at all. Whitelisting the link interface is what fixes it.
#
# Fast DDS 2.6 (Humble) only accepts literal addresses in interfaceWhiteList —
# no CIDR or netmask filters — so the address has to be resolved and baked in
# here. Re-run this whenever the laptop's address on the rover link changes.
#
# The second job: static discovery peers. This originally ran with the WiFi
# adapter plugged straight into the laptop, putting both ends on one L2 segment
# where multicast SPDP discovery just worked. The mast Pi is now an L3 router
# between 10.44.0.0/24 (GS PC) and 10.42.0.0/24 (rover), and routers do not
# forward link-local multicast — so discovery finds nothing at all and the
# topic list comes back empty. initialPeersList replaces the multicast probe
# with a unicast one aimed at a known address.
#
# Only the rover needs listing here. SPDP is symmetric: our announcement
# carries our own unicast locators, so the rover learns how to reach us from
# the first packet it receives and needs no matching config of its own.
#
# The SPDP multicast locator is listed explicitly alongside it, and that is not
# redundant. Fast DDS populates initialPeersList with the multicast locator by
# default, but defining the element *replaces* that default rather than adding
# to it — so listing only the rover silently breaks discovery between nodes on
# this machine. Every ground station node talks to its neighbours over that
# multicast locator, so losing it is far worse than losing the rover: `ros2
# node list` comes back completely empty while the nodes are plainly running.
#
# Usage:
#   ./docker/gen-dds-profile.sh                # probe the default rover subnet
#   ROVER_LINK_PROBE=10.42.0.189 ./docker/gen-dds-profile.sh
#   ROVER_PEER=10.42.0.1 ./docker/gen-dds-profile.sh
set -euo pipefail

PROBE="${ROVER_LINK_PROBE:-10.42.0.0}"
# The rover's address on the wireless segment — where SPDP announcements are
# sent now that multicast cannot reach it.
PEER="${ROVER_PEER:-10.42.0.1}"
DOMAIN="${ROS_DOMAIN_ID:-42}"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/fastdds_rover_link.xml"

# RTPS well-known port for SPDP multicast: PB + DG*domainId + d0,
# with PB=7400, DG=250, d0=0. The port must be spelled out because an initial
# peer with no port makes Fast DDS fan out across participant IDs 0..4, which
# is meaningless for a multicast discovery address.
MCAST_ADDR=239.255.0.1
MCAST_PORT=$((7400 + 250 * DOMAIN))

# `ip route get` answers "which source address would the kernel use to reach
# the rover", which is exactly the address DDS should be announcing.
LINK_IP="$(ip -4 route get "$PROBE" 2>/dev/null | grep -oP '\bsrc \K[0-9.]+' || true)"

if [ -z "$LINK_IP" ]; then
    echo "error: no route to $PROBE — is the rover link adapter up?" >&2
    echo "       interfaces currently up:" >&2
    ip -br -4 addr show | grep -v '^lo' >&2
    exit 1
fi

cat > "$OUT" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by docker/gen-dds-profile.sh — do not edit by hand.
  Rover link address: $LINK_IP (probe: $PROBE)
  Discovery peers:    $MCAST_ADDR:$MCAST_PORT (local, domain $DOMAIN), $PEER (rover)

  Restricts UDP to the rover link so Fast DDS stops announcing locators the
  rover cannot route to. Shared memory is kept alongside it: the ground station
  container talks to a same-host rover_dev/Gazebo container over SHM, and
  dropping the builtin transports without re-adding it would break that.

  initialPeersList adds a unicast peer for the rover, because the mast Pi
  routes between the GS PC and the rover and multicast SPDP does not cross a
  router. The multicast locator is repeated explicitly because defining this
  list replaces Fast DDS's default instead of adding to it, and dropping it
  breaks discovery between the nodes running on this machine.
-->
<dds xmlns="http://www.eprosima.com">
  <profiles>
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>rover_link_udp</transport_id>
        <type>UDPv4</type>
        <interfaceWhiteList>
          <address>$LINK_IP</address>
        </interfaceWhiteList>
      </transport_descriptor>
      <transport_descriptor>
        <transport_id>local_shm</transport_id>
        <type>SHM</type>
      </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="rover_link" is_default_profile="true">
      <rtps>
        <builtin>
          <initialPeersList>
            <!-- Keeps node-to-node discovery working on this machine. -->
            <locator>
              <udpv4>
                <address>$MCAST_ADDR</address>
                <port>$MCAST_PORT</port>
              </udpv4>
            </locator>
            <!-- Reaches the rover, which multicast cannot: the mast Pi routes. -->
            <locator>
              <udpv4>
                <address>$PEER</address>
              </udpv4>
            </locator>
          </initialPeersList>
        </builtin>
        <userTransports>
          <transport_id>rover_link_udp</transport_id>
          <transport_id>local_shm</transport_id>
        </userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
      </rtps>
    </participant>
  </profiles>
</dds>
EOF

echo "wrote $OUT (rover link address: $LINK_IP, discovery peer: $PEER)"
