/**:
  ros__parameters:
    binds: '[{"function": "drive_power", "source": "switches", "index": 6, "invert":
      false}, {"function": "drive_compact", "source": "joy", "index": 8, "invert":
      false}, {"function": "spotlight", "source": "switches", "index": 11, "invert":
      false}, {"function": "beautiful", "source": "switches", "index": 12, "invert":
      false}, {"function": "rover_power_on", "source": "switches", "index": 21, "invert":
      false}, {"function": "rover_power_off", "source": "switches", "index": 16, "invert":
      false}]'
    camera_switches:
    - 2
    - 1
    - 1
