serial_joy_node:
  ros__parameters:
    axis_center:
    - 497.0
    - 491.0
    - 502.0
    - 505.0
    - 502.0
    - 501.0
    axis_map:
    - 5
    - 4
    - 2
    - 3
    - 0
    - 1
    axis_max:
    - 999.0
    - 999.0
    - 999.0
    - 999.0
    - 999.0
    - 999.0
    axis_min:
    - 2.0
    - 0.0
    - 7.0
    - 6.0
    - 4.0
    - 1.0
    axis_scale:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    deadzone: 0.05
