serial_joy_node:
  ros__parameters:
    axis_center:
    - 500.0
    - 500.0
    - 500.0
    - 500.0
    - 500.0
    - 500.0
    axis_map:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    axis_max:
    - 1000.0
    - 1000.0
    - 1000.0
    - 1000.0
    - 1000.0
    - 1000.0
    axis_min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    axis_scale:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    deadzone: 0.05
